// WorldProject – zentrale Übersicht aller gerade laufenden/ausstehenden Betriebsaktivitäten.
import { timeMs, timerEnd, timerStart } from './TimeValueUtils.js';
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const activeStatus=s=>!['finished','completed','cancelled','admin_cancelled','delivered','received','stored','sold','closed','available'].includes(String(s||'').toLowerCase());
const progress=(row,now=Date.now())=>{if(Number(row?.progress)>=0)return Math.max(0,Math.min(100,Math.round(Number(row.progress))));const start=timerStart(row)?.value||0,end=timerEnd(row)?.value||0;if(!start||!end||end<=start)return null;return Math.max(0,Math.min(99,Math.round((now-start)/(end-start)*100)));};
const remaining=(row,now=Date.now())=>{const end=timerEnd(row)?.value||0;return end?Math.max(0,end-now):null;};
function normalize(kind,label,row,now,id=null){return{kind,label:label||row?.label||row?.name||row?.product||row?.recipeId||row?.material||row?.itemId||kind,status:row?.status||'aktiv',progress:progress(row,now),remainingMs:remaining(row,now),id:id??row?.id??row?.instanceId??null,raw:row};}
function machineRows(company={}){const lists=[company.buildingState?.equipment||[],company.productionMachines||[],company.machines||[],company.workforceState?.machines||[],company.workforceOperationsState?.machines||[]],seen=new Set(),rows=[];for(const list of lists)for(const machine of list){if(!machine||machine.status==='sold')continue;const key=String(machine.instanceId??machine.id??`${machine.type||machine.sourceType}:${machine.label||machine.name||''}`);if(seen.has(key))continue;seen.add(key);rows.push(machine);}return rows;}
export function activeOperations(company={},now=Date.now()){
 const rows=[],productionSeen=new Set();
 for(const list of [company.productionJobs||[],company.productionQueue||[],company.operationalSupplyState?.productionQueue||[]])for(const j of list){const key=j?.id||j;if(!j||productionSeen.has(key)||!activeStatus(j.status))continue;productionSeen.add(key);rows.push(normalize('production',j.label||j.recipe?.label||j.product||j.recipe?.product||j.recipeId||'Produktion',j,now));}
 const supply=[...(company.operationalSupplyState?.orders||[]),...(company.supplierOrders||[]),...(company.marketDeliveries||[]),...(company.constructionSite?.deliveries||[])];const seen=new Set();for(const j of supply){const key=j.id||JSON.stringify([j.material||j.item||j.itemId,j.createdAt||j.orderedAt]);if(seen.has(key))continue;seen.add(key);if(activeStatus(j.status))rows.push(normalize('delivery',j.label||j.material||j.item||j.itemId||'Lieferung',j,now));}
 for(const j of company.constructionSite?.jobs||[])if(activeStatus(j.status))rows.push(normalize(j.kind==='land'?'land':'construction',j.label||'Bauprojekt',j,now));
 for(const j of company.warehouseExpansion?.jobs||[])if(activeStatus(j.status))rows.push(normalize('warehouse_expansion',j.label||'Lagerausbau',j,now));
 for(const j of company.machineUpgradeJobs||[])if(activeStatus(j.status))rows.push(normalize('machine_upgrade',j.label||'Maschinenupgrade',j,now));
 for(const j of company.upgradeJobs||[])if(activeStatus(j.status))rows.push(normalize('business_upgrade',`${j.label||'Betriebsausbau'} → Stufe ${j.targetLevel||'?'}`,j,now));
 for(const machine of company.buildingState?.equipment||[]){if(!machine||!['installing','upgrading'].includes(String(machine.status||'').toLowerCase()))continue;const id=machine.instanceId||machine.id;if(id==null||remaining(machine,now)<=0)continue;rows.push(normalize('equipment',`${machine.status==='upgrading'?'Aufrüstung':'Montage'} · ${machine.name||machine.label||machine.id||'Maschine'}`,machine,now,id));}
 for(const machine of machineRows(company)){const job=machine?.maintenanceJob;if(!job||String(job.status||'').toLowerCase()!=='maintenance'||remaining(job,now)<=0)continue;rows.push(normalize('maintenance',`Wartung · ${machine.label||machine.name||machine.id||'Maschine'}`,job,now,job.id));}
 for(const crew of company.warehouseExpansion?.crewBookings||[]){if(!crew||String(crew.status||'').toLowerCase()!=='booked'||remaining(crew,now)<=0)continue;rows.push(normalize('crew_arrival',`Bautrupp-Anfahrt · ${crew.label||'Bautrupp'}`,crew,now,crew.id));}
 for(const j of company.customerOrders||[])if(activeStatus(j.status)&&n(j.remainingQuantity??j.quantity)>0)rows.push(normalize('customer_order',j.label||j.product||'Kundenauftrag',j,now));
 return rows.sort((a,b)=>(a.remainingMs??Infinity)-(b.remainingMs??Infinity));
}
export function activeOperationsSummary(company={},now=Date.now()){const rows=activeOperations(company,now),byType={};for(const r of rows)byType[r.kind]=(byType[r.kind]||0)+1;return{total:rows.length,byType,rows,next:rows.find(x=>x.remainingMs!==null)||null};}
export function runActiveOperationsOverviewTest(){
 const now=Date.parse('2026-08-14T10:00:00Z');const c={productionJobs:[{id:1,status:'running',startedAt:new Date(now-1000).toISOString(),finishAt:new Date(now+1000).toISOString(),label:'Pils'}],productionQueue:[{id:5,status:'running',startedAt:now-100,completeAt:now+1500,recipeId:'lager'}],supplierOrders:[{id:6,status:'in_transit',orderedAt:new Date(now-5000).toISOString(),arrivalAt:new Date(now+5000).toISOString(),itemId:'malt'}],marketDeliveries:[{id:7,status:'in_transit',orderedAt:now-1000,arrivalTime:new Date(now+7000),material:'caps',kind:'market_goods'}],machineUpgradeJobs:[{id:2,status:'upgrading',startedAt:now-1000,finishAt:now+2000,label:'Tank'}],upgradeJobs:[{id:4,status:'running',startedAt:now-100,finishAt:now+3000,label:'Produktionsleistung',targetLevel:2}],customerOrders:[{id:3,status:'open',quantity:10,product:'Bier'}],buildingState:{equipment:[{instanceId:'eq1',id:'brewhouse',name:'Sudhaus',status:'installing',installationStartedAt:now-1000,installationFinishAt:now+6000,maintenanceJob:null},{instanceId:'eq2',id:'washer',name:'Wascher',status:'maintenance',maintenanceJob:{id:'maint1',status:'maintenance',startedAt:now-1000,completeAt:now+9000}}]},warehouseExpansion:{jobs:[],crewBookings:[{id:'crew1',label:'Bau Nord',status:'booked',bookedAt:now-500,availableAt:now+11000}]},constructionSite:{jobs:[],deliveries:[{id:'mat1',kind:'construction_material_order',status:'in_transit',orderedAt:now-1000,arrivesAt:now+10000,item:'steel'}]}};
 const s=activeOperationsSummary(c,now);if(s.total!==11||s.byType.production!==2||s.byType.delivery!==3||s.byType.machine_upgrade!==1||s.byType.business_upgrade!==1||s.byType.equipment!==1||s.byType.maintenance!==1||s.byType.crew_arrival!==1||s.byType.customer_order!==1)throw new Error('Aktivitaetsuebersicht fehlerhaft');const deliveries=s.rows.filter(r=>r.kind==='delivery');if(!deliveries.some(x=>x.id===6&&x.remainingMs===5000)||!deliveries.some(x=>x.id===7&&x.remainingMs===7000)||!deliveries.some(x=>x.id==='mat1'&&x.remainingMs===10000))throw new Error('Persistierte Lieferzeit wird nicht erkannt');const nested={operationalSupplyState:{productionQueue:[{id:'nested',status:'running',startedAt:now-1000,finishAt:now+8000,recipe:{label:'Lagerbier 0,33 l'}}]}};const nestedSummary=activeOperationsSummary(nested,now);if(nestedSummary.total!==1||nestedSummary.rows[0].kind!=='production'||nestedSummary.rows[0].remainingMs!==8000)throw new Error('Operative Produktionswarteschlange fehlt in Übersicht');if(timeMs(c.productionJobs[0].finishAt)!==now+1000)throw new Error('ISO-Zeitwert fehlerhaft');return true;}
if(typeof window!=='undefined')window.worldActiveOperations={list:activeOperations,summary:activeOperationsSummary,runTest:runActiveOperationsOverviewTest};
