// ORVUNO – Newsletter-/Nachrichtenwerkzeug im bestehenden In-Game-Admin.
(function(){
'use strict';if(window.__ORVUNO_ADMIN_NEWSLETTER_V1__)return;window.__ORVUNO_ADMIN_NEWSLETTER_V1__=true;
const ENDPOINT='https://ojhaeccyulyrwoxgeurf.supabase.co/functions/v1/orvuno-admin-messages';let players=[],busy=false;
const client=()=>window.worldAccounts?.authApi||null;
async function call(action,payload={}){const api=client();const t=await api?.ensureAccessToken?.();if(!t)throw Error('Admin-Sitzung abgelaufen.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+t},body:JSON.stringify({action,...payload}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function install(){if(document.getElementById('orvunoAdminNewsletterButton'))return;if(!document.querySelector('.oa-root'))return;const s=document.createElement('style');s.id='orvunoAdminNewsletterStyle';s.textContent=`#orvunoAdminNewsletterButton{position:fixed;right:178px;top:14px;z-index:100003;border:1px solid #d29922;border-radius:8px;padding:8px 11px;background:#2d2110;color:#ffd866;font-weight:900;cursor:pointer}#orvunoAdminNewsletterModal{position:fixed;inset:0;z-index:100010;display:none;place-items:center;padding:14px;background:#02050bd9}#orvunoAdminNewsletterModal.show{display:grid}.oaNlCard{width:min(720px,96vw);max-height:90vh;overflow:auto;padding:20px;border:1px solid #475569;border-radius:16px;background:#111827;color:#e5edf7;box-shadow:0 28px 90px #000d}.oaNlHead{display:flex;justify-content:space-between;align-items:center;gap:12px}.oaNlHead h2{margin:0}.oaNlClose{border:0;background:transparent;color:#fff;font-size:27px;cursor:pointer}.oaNlGrid{display:grid;gap:12px;margin-top:16px}.oaNlGrid label{display:grid;gap:6px;color:#b7c3d1;font-size:12px;font-weight:800}.oaNlGrid input,.oaNlGrid select,.oaNlGrid textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #475569;border-radius:8px;background:#0f172a;color:#fff}.oaNlGrid textarea{min-height:160px;resize:vertical}.oaNlSend{padding:9px 12px;border:1px solid #d29922;border-radius:8px;background:#2d2110;color:#ffd866;font-weight:900;cursor:pointer}.oaNlSend:disabled{opacity:.5}.oaNlStatus{font-size:12px;color:#aebdce}.oaNlStatus.ok{color:#86e5a7}.oaNlStatus.bad{color:#ff9aaa}@media(max-width:700px){#orvunoAdminNewsletterButton{right:18px;top:60px}}`;document.head.append(s);const b=document.createElement('button');b.id='orvunoAdminNewsletterButton';b.type='button';b.textContent='✉ Nachrichten';b.onclick=open;document.body.append(b);const m=document.createElement('div');m.id='orvunoAdminNewsletterModal';m.innerHTML='<section class="oaNlCard"><div class="oaNlHead"><div><small>IN-GAME NEWSLETTER</small><h2>Nachrichten an ORVUNO-Spieler</h2></div><button type="button" id="oaNlClose" class="oaNlClose">×</button></div><div class="oaNlGrid"><label>Empfänger<select id="oaNlMode"><option value="all">Alle ORVUNO-Spieler</option><option value="one">Einzelner Spieler</option></select></label><label id="oaNlPlayerRow" hidden>Spieler<select id="oaNlPlayer"><option value="">Spieler wählen …</option></select></label><label>Betreff<input id="oaNlSubject" maxlength="160"></label><label>Nachricht<textarea id="oaNlBody" maxlength="10000"></textarea></label><div><button id="oaNlSend" class="oaNlSend" type="button">Nachricht senden</button> <span id="oaNlStatus" class="oaNlStatus"></span></div></div></section>';m.addEventListener('click',e=>{if(e.target===m)close()});document.body.append(m);document.getElementById('oaNlClose').onclick=close;document.getElementById('oaNlMode').onchange=syncMode;document.getElementById('oaNlSend').onclick=send}
function syncMode(){document.getElementById('oaNlPlayerRow').hidden=document.getElementById('oaNlMode').value!=='one'}function status(t,c=''){const e=document.getElementById('oaNlStatus');if(e){e.textContent=t||'';e.className='oaNlStatus'+(c?' '+c:'')}}
async function loadPlayers(){try{const d=await call('list_players');players=Array.isArray(d.players)?d.players:[];const s=document.getElementById('oaNlPlayer');if(s)s.innerHTML='<option value="">Spieler wählen …</option>'+players.map(p=>`<option value="${esc(p.id)}">${esc(p.display_name||p.username||p.email||'Spieler')}</option>`).join('')}catch(e){status(e.message,'bad')}}
async function send(){if(busy)return;const mode=document.getElementById('oaNlMode').value,subject=document.getElementById('oaNlSubject').value.trim(),body=document.getElementById('oaNlBody').value.trim(),playerId=document.getElementById('oaNlPlayer').value;if(!subject||!body)return status('Bitte Betreff und Nachricht ausfüllen.','bad');if(mode==='one'&&!playerId)return status('Bitte einen Spieler auswählen.','bad');if(mode==='all'&&!confirm('Diese Nachricht wirklich an ALLE ORVUNO-Spieler senden?'))return;busy=true;document.getElementById('oaNlSend').disabled=true;status('Nachricht wird gespeichert …');try{await call(mode==='all'?'send_all':'send_one',{subject,body,playerId});document.getElementById('oaNlSubject').value='';document.getElementById('oaNlBody').value='';status('✅ Nachricht erfolgreich gesendet.','ok')}catch(e){status('Versand fehlgeschlagen: '+e.message,'bad')}finally{busy=false;document.getElementById('oaNlSend').disabled=false}}
function open(){install();document.getElementById('orvunoAdminNewsletterModal')?.classList.add('show');void loadPlayers()}function close(){document.getElementById('orvunoAdminNewsletterModal')?.classList.remove('show')}
function sync(){if(document.querySelector('.oa-root'))install();else{document.getElementById('orvunoAdminNewsletterButton')?.remove();document.getElementById('orvunoAdminNewsletterModal')?.remove();document.getElementById('orvunoAdminNewsletterStyle')?.remove()}}
window.addEventListener('world:admin-opened',()=>setTimeout(sync,0));window.addEventListener('world:admin-closed',sync);new MutationObserver(sync).observe(document.documentElement,{childList:true,subtree:true});
})();
