// WorldProject - Supabase Auth + Data API Client
const SUPABASE_URL = "https://ojhaeccyulyrwoxgeurf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_JZH6Ker5-yZoNY6sQFhVTA_YKnImI3z";
const SESSION_KEY = "worldproject_supabase_session";
const RECOVERY_FLAG_KEY = "worldproject_password_recovery";
const LOCAL_SESSION_KEY = "orvuno_hetzner_session";
export class AuthApiClient {
 constructor({baseUrl=SUPABASE_URL,publishableKey=SUPABASE_PUBLISHABLE_KEY,localApiBase="/api/orvuno"}={}){this.baseUrl=baseUrl.replace(/\/$/,"");this.publishableKey=publishableKey;this.localApiBase=String(localApiBase||"/api/orvuno").replace(/\/$/,"");this.session=this.loadSession();this.localSession=this.loadLocalSession();this.captureSessionFromUrl();}
 loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null");}catch{return null;}} saveSession(s){this.session=s||null;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY);} loadLocalSession(){try{return JSON.parse(localStorage.getItem(LOCAL_SESSION_KEY)||"null");}catch{return null;}} saveLocalSession(s){this.localSession=s||null;if(s)localStorage.setItem(LOCAL_SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(LOCAL_SESSION_KEY);} localSessionValid(){const exp=Date.parse(this.localSession?.expiresAt||"");return !!this.localSession?.token&&Number.isFinite(exp)&&exp>Date.now()+30000;}
 captureSessionFromUrl(){const raw=location.hash?.replace(/^#/,"");if(!raw)return null;const p=new URLSearchParams(raw),access_token=p.get("access_token"),refresh_token=p.get("refresh_token");if(!access_token)return null;const type=p.get("type")||null,s={access_token,refresh_token,expires_in:Number(p.get("expires_in")||3600),token_type:p.get("token_type")||"bearer",expires_at:Math.floor(Date.now()/1000)+Number(p.get("expires_in")||3600),type};this.saveLocalSession(null);this.saveSession(s);if(type==="recovery"){try{sessionStorage.setItem(RECOVERY_FLAG_KEY,"1");}catch{}}history.replaceState(null,document.title,location.pathname+location.search);return s;}
 isPasswordRecovery(){try{return this.session?.type==="recovery"||sessionStorage.getItem(RECOVERY_FLAG_KEY)==="1";}catch{return this.session?.type==="recovery";}}
 async preparePasswordRecovery(){if(this.isPasswordRecovery())return true;const q=new URLSearchParams(location.search),code=q.get("code");if(!code)return false;const verifier=(()=>{try{return sessionStorage.getItem("worldproject_pkce_verifier")||localStorage.getItem("worldproject_pkce_verifier")||"";}catch{return "";}})();const payload={auth_code:code};if(verifier)payload.code_verifier=verifier;const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=pkce`,{method:"POST",headers:this.headers(),body:JSON.stringify(payload)}),b=await this.parse(r);this.saveSession({...b,type:"recovery"});try{sessionStorage.setItem(RECOVERY_FLAG_KEY,"1");sessionStorage.removeItem("worldproject_pkce_verifier");localStorage.removeItem("worldproject_pkce_verifier");}catch{}q.delete("code");const search=q.toString();history.replaceState(null,document.title,`${location.pathname}${search?`?${search}`:""}${location.hash||""}`);return true;}
 clearPasswordRecovery(){if(this.session?.type==="recovery")this.saveSession({...this.session,type:null});try{sessionStorage.removeItem(RECOVERY_FLAG_KEY);}catch{}}
 headers({auth=false,json=true}={}){const h={apikey:this.publishableKey};if(json)h["Content-Type"]="application/json";if(auth&&this.session?.access_token)h.Authorization=`Bearer ${this.session.access_token}`;return h;}async parse(r){const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.msg||b.message||b.error_description||b.error||`HTTP ${r.status}`);return b;}
 async health(){try{const r=await fetch(`${this.localApiBase}/health`,{headers:{Accept:"application/json"},cache:"no-store"});if(r.ok)return{success:true,mode:"hetzner"};}catch{}const r=await fetch(`${this.baseUrl}/auth/v1/health`,{headers:this.headers({json:false})});if(!r.ok)throw new Error("Spielserver nicht erreichbar");return{success:true,mode:"supabase-fallback"};}
 async register(d){const r=await fetch(`${this.baseUrl}/auth/v1/signup`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:d.email,password:d.password,data:{username:d.username,country_code:d.countryCode||"DE",language_code:d.languageCode||"de",terms_version:"1.0",privacy_version:"1.0"}})}),b=await this.parse(r);if(b.access_token){this.saveLocalSession(null);this.saveSession(b);}return{success:true,user:b.user,session:b.access_token?b:null,confirmationRequired:!b.access_token};}
 async login({email,password,emailOrUsername}={}){const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=password`,{method:"POST",headers:this.headers(),body:JSON.stringify({email:email||emailOrUsername,password})}),b=await this.parse(r);this.saveLocalSession(null);this.saveSession(b);return{success:true,user:await this.me()};}
 async refreshSession(){const token=this.session?.refresh_token;if(!token)throw new Error("Keine Sitzung vorhanden");const r=await fetch(`${this.baseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:this.headers(),body:JSON.stringify({refresh_token:token})}),b=await this.parse(r);this.saveSession(b);return b;}async ensureAccessToken(){if(!this.session?.access_token)return null;const exp=Number(this.session.expires_at||0);if(exp&&exp-60>Math.floor(Date.now()/1000))return this.session.access_token;try{await this.refreshSession();return this.session?.access_token||null;}catch{this.saveSession(null);return null;}}
 async authRequest(path,o={}){if(!await this.ensureAccessToken())throw new Error("Nicht angemeldet");const r=await fetch(`${this.baseUrl}${path}`,{...o,headers:{...this.headers({auth:true}),...(o.headers||{})}});return this.parse(r);}
 async rest(path,o={}){return this.authRequest(`/rest/v1/${path}`,o);}
 async ensureLocalSession({force=false}={}){if(!force&&this.localSessionValid())return this.localSession.token;const supabaseToken=await this.ensureAccessToken();if(!supabaseToken)return null;try{const r=await fetch(`${this.localApiBase}/session/exchange`,{method:"POST",headers:{Authorization:`Bearer ${supabaseToken}`,"Accept":"application/json"},cache:"no-store"}),payload=await r.json().catch(()=>({}));if(!r.ok||payload?.success===false||!payload?.token)throw new Error(payload?.error||payload?.message||`HTTP ${r.status}`);this.saveLocalSession({token:payload.token,expiresAt:payload.expiresAt||null});return payload.token;}catch(error){console.warn("Hetzner-Spielsitzung konnte noch nicht erstellt werden; Supabase-Fallback bleibt aktiv",error);return null;}}
 async syncLocalEntitlements(){this.saveLocalSession(null);return this.ensureLocalSession({force:true});}
 async localRequest(path,{method="GET",body=null,headers={}}={}){let token=await this.ensureLocalSession();if(!token)token=await this.ensureAccessToken();if(!token)throw new Error("Nicht angemeldet");const makeRequest=async bearer=>{const opts={method,headers:{Authorization:`Bearer ${bearer}`,"Accept":"application/json",...headers},cache:"no-store"};if(body!==null){opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(body);}const r=await fetch(`${this.localApiBase}/${String(path||"").replace(/^\//,"")}`,opts),payload=await r.json().catch(()=>({}));return{r,payload};};let {r,payload}=await makeRequest(token);if(r.status===401&&this.localSession?.token&&token===this.localSession.token){this.saveLocalSession(null);const fallback=await this.ensureAccessToken();if(fallback){({r,payload}=await makeRequest(fallback));}}if(!r.ok||payload?.success===false)throw new Error(payload?.error||payload?.message||`HTTP ${r.status}`);return payload;}
 async rpc(n,d={}){if(n==="shorten_company_timed_action")return this.localRequest("coins/time-reduction",{method:"POST",body:{companyId:Number(d.p_company_id),actionKind:d.p_action_kind,actionId:String(d.p_action_id||""),hours:Number(d.p_hours||1),maxCoins:d.p_max_coins==null?null:Number(d.p_max_coins)}});if(n==="exchange_coins_for_company_money_v2")return this.localRequest("coins/exchange",{method:"POST",body:{tier:d.p_tier,requestId:d.p_request_id}});return this.rest(`rpc/${n}`,{method:"POST",body:JSON.stringify(d)});}
 async localAccountOverview(){return this.localRequest("account");}
 async me(){const overview=await this.localAccountOverview(),user=overview?.user;if(!user)throw new Error("Spielerprofil wurde noch nicht angelegt");return user;}
 async processBusinessFinances(){const result=await this.localRequest("business/process-finances",{method:"POST",body:{}});return{success:true,events:Array.isArray(result?.events)?result.events:[],processedAt:Number(result?.processedAt||0),source:result?.source||"hetzner"};}
 async accountOverview(){return this.localAccountOverview();}
 async markTutorialSeen({completed=false}={}){const result=await this.localRequest("tutorial",{method:"POST",body:{completed:!!completed}});if(typeof window!=="undefined"){const patch={tutorial_seen_at:result?.tutorialSeenAt||window.worldCurrentUser?.tutorial_seen_at||new Date().toISOString()};if(result?.tutorialCompletedAt)patch.tutorial_completed_at=result.tutorialCompletedAt;window.worldCurrentUser={...(window.worldCurrentUser||{}),...patch};window.dispatchEvent(new CustomEvent("world:profile-updated",{detail:{user:window.worldCurrentUser}}));}return result;}
 async markTutorialCompleted(){return this.markTutorialSeen({completed:true});}
 async logout(){try{if(this.localSession?.token)try{await fetch(`${this.localApiBase}/session/logout`,{method:"POST",headers:{Authorization:`Bearer ${this.localSession.token}`,"Accept":"application/json"},cache:"no-store"});}catch{}if(this.session?.access_token)await fetch(`${this.baseUrl}/auth/v1/logout`,{method:"POST",headers:this.headers({auth:true})});}finally{this.saveLocalSession(null);this.saveSession(null);this.clearPasswordRecovery();}return{success:true};}async resendVerification(email){const r=await fetch(`${this.baseUrl}/auth/v1/resend`,{method:"POST",headers:this.headers(),body:JSON.stringify({type:"signup",email})});await this.parse(r);return{success:true};}async requestPasswordReset(email){const r=await fetch(`${this.baseUrl}/auth/v1/recover`,{method:"POST",headers:this.headers(),body:JSON.stringify({email})});await this.parse(r);return{success:true};}async resetPassword(_t,password){if(!password||String(password).length<10)throw new Error("Passwort muss mindestens 10 Zeichen haben");const r=await fetch(`${this.baseUrl}/auth/v1/user`,{method:"PUT",headers:this.headers({auth:true}),body:JSON.stringify({password})});await this.parse(r);this.clearPasswordRecovery();return{success:true};}
 async updateProfile(d){const result=await this.localRequest("profile",{method:"PATCH",body:d||{}}),user=result?.user||null;if(user&&typeof window!=="undefined"){window.worldCurrentUser={...(window.worldCurrentUser||{}),...user};window.dispatchEvent(new CustomEvent("world:profile-updated",{detail:{user:window.worldCurrentUser}}));}return{success:true,user,source:result?.source||"hetzner"};}
 async getPremiumStatus(){const u=await this.me();return{success:true,premium:{plan:u.premiumPlan,until:u.premiumUntil,autoRenew:u.premiumAutoRenew,active:Number(u.premiumUntil||0)>Date.now()}};}
 async savePremiumStatus({plan=null,until=0,autoRenew=false}={}){const u=await this.me(),payload={premium_plan:plan||null,premium_until:Number(until)>0?new Date(Number(until)).toISOString():null,premium_auto_renew:!!autoRenew};const r=await this.rest(`users?auth_user_id=eq.${encodeURIComponent(u.auth_user_id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}),row=r?.[0]||{};return{success:true,premium:{plan:row.premium_plan||null,until:row.premium_until?new Date(row.premium_until).getTime():0,autoRenew:!!row.premium_auto_renew}};}
 async ensureCompany(d={}){return this.localRequest("business/ensure",{method:"POST",body:{name:d.name||null,industry:d.industry||null,companyType:d.companyType||d.type||null}});}
 async createBusiness(d={}){return this.localRequest("business/create",{method:"POST",body:{name:d.name||null,industry:d.industry||null,companyType:d.companyType||d.type||null,slotNo:Number(d.slotNo)}});}
 async createPaidBusiness(d={}){const sourceId=d.sourceCompanyId||d.sourceCompany?.serverCompanyId||d.sourceCompany?.id;if(!sourceId)throw new Error("Quellbetrieb für bezahlte Expansion fehlt");return this.localRequest("business/create-paid",{method:"POST",body:{name:d.name||null,industry:d.industry||null,companyType:d.companyType||d.type||null,slotNo:Number(d.slotNo),sourceCompanyId:Number(sourceId),locationClass:d.locationClass||"smallTown",propertyMode:d.propertyMode==="buy"?"buy":"rent",propertySizeLevel:Math.max(1,Number(d.propertySizeLevel||1))}});}
 async saveGameState(s){return this.localRequest("save-game-state",{method:"POST",body:{state:s||{}}});}
 async saveBusinessState(id,s){return this.localRequest("save-business-state",{method:"POST",body:{companyId:Number(id),state:s||{}}});}
 async updateBusinessSetup(id,p,b){return this.localRequest("business/setup",{method:"POST",body:{companyId:Number(id),setupPhase:p,buildingState:b||{}}});}
 async transferBusinessMoney(a,b,x){return this.localRequest("business/transfer",{method:"POST",body:{fromCompanyId:Number(a),toCompanyId:Number(b),amount:Number(x)}});}
 async listInternalTransfers(){const result=await this.localRequest("business/transfers");return result?.rows||[];}
 async listExpansionLoans(){const result=await this.localRequest("business/loans");return result?.rows||[];}
 async takeExpansionLoan(companyId,offer){const result=await this.localRequest("business/loan",{method:"POST",body:{companyId:Number(companyId),amount:Number(offer.amount),termMonths:Number(offer.termMonths)}});return{success:true,loan:result?.loan||result};}
 async listCoinOrders(){const result=await this.localRequest("coins/orders");return result?.rows||[];}
 async createCoinSellOrder(a,p){const result=await this.localRequest("coins/order/create",{method:"POST",body:{amount:Number(a),pricePerCoin:Number(p)}});return{success:true,orderId:result?.orderId};}
 async cancelCoinSellOrder(id){const result=await this.localRequest("coins/order/cancel",{method:"POST",body:{orderId:Number(id)}});return{success:true,balance:result?.balance};}
 async buyCoinOrder(id,a){const result=await this.localRequest("coins/order/buy",{method:"POST",body:{orderId:Number(id),amount:Number(a)}});if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("world:server-balances-changed",{detail:result}));return{success:true,trade:result?.trade||result};}

}
