import { PremiumEntitlementSystem } from './PremiumEntitlementSystem.js';
import { timerEnd,shiftKnownEndTimes } from './TimeValueUtils.js';
import { COIN_TIME_RULE_LABEL,coinCostForMs,operationTimeReductionQuoteForCoins,reduceOperationTimeWithCoins } from './OperationCoinTimeReductionSystem.js';

export const COIN_TIME_REDUCTION=Object.freeze({minHours:1,maxHours:10,minutesPerCoin:5,coinsPerFiveMinutes:1,coinsPerHour:12,maxCoinsPerPurchase:120,minimumRealTimeRatio:0});
const premium=new PremiumEntitlementSystem();
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const account=()=>typeof window!=='undefined'?(window.worldCurrentUser||window.worldAccount||{}):{};

export function activeConstructionJobs(company={}){return(company?.constructionSite?.jobs||[]).filter(j=>j&&j.status==='building');}
export function constructionSlotState(company={},a=account(),now=Date.now()){const running=activeConstructionJobs(company).length,limit=premium.constructionLimit(a,now);return{running,limit,free:Math.max(0,limit-running),premium:premium.state(a,now).active,allowed:running<limit};}
export function assertCanStartConstruction(company={},a=account(),now=Date.now()){const s=constructionSlotState(company,a,now);if(!s.allowed)throw new Error(`Maximal ${s.limit} parallele Bauauftraege erlaubt.${s.premium?'':' Premium erweitert das Limit auf 5.'}`);return s;}
export function constructionMinimumFinishAt(job={}){return n(job?.startedAt||job?.startTime||job?.createdAt);}
function actionKind(job={}){const kind=String(job?.kind||'').toLowerCase();if(kind==='land')return'land';if(kind==='warehouse_expansion')return'warehouse_expansion';if(kind==='machine_upgrade')return'machine_upgrade';if(kind==='business_upgrade')return'business_upgrade';return'construction';}
function operationRow(job={},now=Date.now()){const end=timerEnd(job)?.value||0;return{kind:actionKind(job),id:job.id??job.instanceId,raw:job,remainingMs:Math.max(0,end-now)};}

export function timeReductionQuote(company={},job,hours=1,{now=Date.now()}={}){
 if(!job||!['building','upgrading','running'].includes(String(job.status||'').toLowerCase()))throw new Error('Dieser Vorgang kann nicht mehr verkuerzt werden');
 const end=timerEnd(job)?.value||0,remainingMs=Math.max(0,end-now);if(!remainingMs)throw new Error('Der Vorgang ist bereits fertig');
 const requested=Math.max(1,Math.min(87600,Math.floor(n(hours,1)))),reductionMs=Math.min(remainingMs,requested*3600000),cost=coinCostForMs(reductionMs);
 return{hours:requested,cost,remainingMs,reductionMs,newRemainingMs:remainingMs-reductionMs,coins:n(company.coins),minimumFinishAt:now,minimumRealTimeMs:0,locked:false,priceUnitMinutes:5};
}
// Legacy-Helfer fuer alte interne Aufrufer. Sichtbare Spieleraktionen nutzen den serverautoritativen Dialog unten.
export function reduceJobTimeWithCoins(company={},job,hours=1,{now=Date.now()}={}){
 const q=timeReductionQuote(company,job,hours,{now});if(n(company.coins)<q.cost)throw new Error(`Nicht genug Coins. Benoetigt: ${q.cost}, vorhanden: ${n(company.coins)}`);
 company.coins=n(company.coins)-q.cost;shiftKnownEndTimes(job,-q.reductionMs,{floorMs:now});job.coinTimeReductionMs=n(job.coinTimeReductionMs)+q.reductionMs;job.coinTimeReductionSpent=n(job.coinTimeReductionSpent)+q.cost;job.lastCoinTimeReductionAt=now;job.coinAccelerationPolicy='one-coin-per-started-five-minutes';
 return{...q,finishAt:timerEnd(job)?.value||now,coinsAfter:company.coins};
}
const fmt=ms=>{let m=Math.max(0,Math.ceil(n(ms)/60000)),h=Math.floor(m/60);return h?`${h} Std. ${m%60} Min.`:`${m} Min.`;};
export function openCoinTimeReductionDialog({company,job,onDone=()=>{},parent=document.body}={}){
 if(typeof document==='undefined')return null;const row=operationRow(job),end=timerEnd(job)?.value||0;if(!row.id||!end||end<=Date.now())throw new Error('Dieser Vorgang ist bereits fertig');
 const ov=document.createElement('div'),p=document.createElement('div'),cancel=document.createElement('button'),buy=document.createElement('button'),input=document.createElement('input'),preview=document.createElement('div');Object.assign(ov.style,{position:'fixed',inset:0,zIndex:30000,background:'rgba(0,0,0,.72)',display:'flex',alignItems:'center',justifyContent:'center',padding:'14px'});Object.assign(p.style,{width:'min(560px,94vw)',background:'#111827',color:'#fff',padding:'18px',borderRadius:'14px',boxSizing:'border-box'});
 const remainingMs=Math.max(0,end-Date.now()),fullCost=coinCostForMs(remainingMs),balance=Math.max(0,Math.floor(Number(company?.coins||0))),initial=Math.min(fullCost,balance);p.innerHTML=`<h2 style="margin-top:0">🪙 Zeit verkürzen</h2><b>${job.label||'Vorgang'}</b><div style="margin:10px 0;color:#fde68a"><strong>${COIN_TIME_RULE_LABEL}</strong><br>Du bestimmst selbst, wie viele Coins du einsetzen willst. Normales Warten bleibt kostenlos.</div><div>Restzeit: <b>${fmt(remainingMs)}</b><br>Ganz fertig: <b>${fullCost} Coin${fullCost===1?'':'s'}</b><br>Coin-Guthaben: <b>${balance}</b></div>`;
 const chooser=document.createElement('div');Object.assign(chooser.style,{display:'flex',alignItems:'center',gap:'8px',flexWrap:'wrap',margin:'14px 0'});const label=document.createElement('label');label.textContent='Coins einsetzen:';label.style.fontWeight='800';input.type='number';input.min='1';input.step='1';input.dataset.orvunoConstructionCoinBudget='1';input.value=String(initial>0?initial:1);Object.assign(input.style,{width:'80px',padding:'7px',borderRadius:'6px',border:'1px solid #d6a52d',fontWeight:'800'});Object.assign(preview.style,{fontSize:'13px',fontWeight:'800',color:'#fde68a',flex:'1 1 220px'});chooser.append(label,input,preview);p.append(chooser);
 cancel.textContent='Abbrechen';cancel.onclick=()=>ov.remove();Object.assign(buy.style,{marginLeft:'8px',fontWeight:'800'});
 const update=()=>{const fresh=operationRow(job),freshEnd=timerEnd(job)?.value||0;if(!fresh.id||freshEnd<=Date.now()){buy.disabled=true;input.disabled=true;preview.textContent='Vorgang ist bereits fertig.';return null;}const full=coinCostForMs(Math.max(0,freshEnd-Date.now())),coins=Math.max(0,Math.floor(Number(company?.coins||0))),maxSpend=Math.min(full,coins);input.max=String(Math.max(1,maxSpend));if(maxSpend<=0){input.disabled=true;buy.disabled=true;preview.textContent='Keine Coins verfügbar.';buy.textContent='⚡ Keine Coins verfügbar';return null;}input.disabled=false;let selected=Math.floor(Number(input.value)||1);selected=Math.max(1,Math.min(maxSpend,selected));input.value=String(selected);const q=operationTimeReductionQuoteForCoins(fresh,selected);preview.textContent=`${q.costCoins} Coin${q.costCoins===1?'':'s'} = ${fmt(q.reducedMs)} weniger · danach ca. ${fmt(q.newRemainingMs)} Restzeit`;buy.textContent=q.full?`⚡ Sofort fertig · ${q.costCoins} Coin${q.costCoins===1?'':'s'}`:`⚡ ${fmt(q.reducedMs)} verkürzen · ${q.costCoins} Coin${q.costCoins===1?'':'s'}`;buy.disabled=false;return{fresh,q,selected};};
 input.oninput=update;input.onchange=update;update();
 buy.onclick=async()=>{const state=update();if(!state)return;const {fresh,q,selected}=state;if(!confirm(`${q.full?'Diesen Vorgang jetzt vollständig abschließen?':`Diesen Vorgang um ${fmt(q.reducedMs)} verkürzen?`}\n\nEinsatz: ${q.costCoins} Coin${q.costCoins===1?'':'s'}\nRestzeit danach: ca. ${fmt(q.newRemainingMs)}\n${COIN_TIME_RULE_LABEL}`))return;buy.disabled=true;buy.textContent='Wird gebucht…';try{const result=await reduceOperationTimeWithCoins(company,fresh,'all',{coinBudget:selected});ov.remove();onDone(result);}catch(e){alert(e.message);update();}};
 p.append(document.createElement('hr'),cancel,buy);ov.append(p);parent.append(ov);return ov;
}
export function runConstructionPremiumCoinTest(){const now=1000000,c={coins:10},j={id:'c1',status:'building',finishAt:now+90*60000};const q=timeReductionQuote(c,j,2,{now});if(q.cost!==18)throw new Error('90 Minuten müssen 18 Coins kosten');const partial=operationTimeReductionQuoteForCoins(operationRow(j,now),10,{now});if(partial.costCoins!==10||partial.reducedMs!==50*60000||partial.newRemainingMs!==40*60000)throw new Error('10 Coins müssen 50 von 90 Minuten verkürzen');return true;}
if(typeof window!=='undefined')window.worldConstructionPremiumCoin={config:COIN_TIME_REDUCTION,slotState:constructionSlotState,assertCanStart:assertCanStartConstruction,quote:timeReductionQuote,reduce:reduceJobTimeWithCoins,minimumFinishAt:constructionMinimumFinishAt,openDialog:openCoinTimeReductionDialog,runTest:runConstructionPremiumCoinTest};
