// ORVUNO – In-Game-Postfach für Nachrichten von Nadena Games / Administration.
(function(){
'use strict';
if(window.__ORVUNO_ADMIN_MESSAGES_V1__)return;window.__ORVUNO_ADMIN_MESSAGES_V1__=true;
let items=[],busy=false,lastLoad=0;
const api=()=>window.worldAccounts?.authApi||null;
function install(){
 if(document.getElementById('orvunoAdminInboxButton'))return;
 const style=document.createElement('style');style.textContent=`
 #orvunoAdminInboxButton{position:fixed;right:18px;bottom:18px;z-index:99970;width:50px;height:50px;border:1px solid #d7a62b;border-radius:15px;background:linear-gradient(145deg,#16253b,#263a55);color:#fff;font-size:22px;box-shadow:0 10px 30px #0008;cursor:pointer}#orvunoAdminInboxBadge{position:absolute;right:-5px;top:-6px;min-width:20px;height:20px;padding:0 5px;display:none;place-items:center;border-radius:999px;background:#c74652;color:#fff;border:2px solid #07101d;font:900 10px system-ui}
 #orvunoAdminInboxModal{position:fixed;inset:0;z-index:99990;display:none;place-items:center;padding:14px;background:#020509d4}#orvunoAdminInboxModal.show{display:grid}.orvunoInboxCard{width:min(720px,96vw);max-height:88vh;display:flex;flex-direction:column;overflow:hidden;border:1px solid #49617c;border-radius:18px;background:#0c1624;color:#eef4fb;box-shadow:0 28px 85px #000c}.orvunoInboxHead{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-bottom:1px solid #263a50}.orvunoInboxHead h2{margin:0;font-size:20px}.orvunoInboxHead button{border:0;background:transparent;color:#fff;font-size:27px;cursor:pointer}.orvunoInboxList{display:grid;gap:10px;padding:14px;overflow:auto}.orvunoInboxMsg{padding:14px;border:1px solid #2e4055;border-radius:13px;background:#111f31;cursor:pointer}.orvunoInboxMsg.unread{border-color:#d7a62b;box-shadow:inset 4px 0 #f4bd43;background:#202317}.orvunoInboxMsg h3{margin:0 0 5px}.orvunoInboxMeta{font-size:11px;color:#9fb0c2}.orvunoInboxBody{margin-top:10px;white-space:pre-wrap;line-height:1.55;font-size:13px}.orvunoInboxEmpty{text-align:center;padding:30px;color:#9fb0c2}@media(max-width:720px){#orvunoAdminInboxButton{right:10px;bottom:74px}}
 `;document.head.append(style);
 const b=document.createElement('button');b.id='orvunoAdminInboxButton';b.type='button';b.title='Nachrichten';b.innerHTML='✉️<span id="orvunoAdminInboxBadge"></span>';b.onclick=open;document.body.append(b);
 const modal=document.createElement('div');modal.id='orvunoAdminInboxModal';modal.innerHTML='<section class="orvunoInboxCard"><header class="orvunoInboxHead"><h2>✉️ Nachrichten von Nadena Games</h2><button id="orvunoAdminInboxClose" type="button">×</button></header><div id="orvunoAdminInboxList" class="orvunoInboxList"></div></section>';modal.addEventListener('click',e=>{if(e.target===modal)close()});document.body.append(modal);document.getElementById('orvunoAdminInboxClose').onclick=close;
}
function badge(){const b=document.getElementById('orvunoAdminInboxBadge');if(!b)return;const n=items.filter(x=>!x.read_at).length;b.textContent=n>99?'99+':String(n);b.style.display=n?'grid':'none'}
function render(){const host=document.getElementById('orvunoAdminInboxList');if(!host)return;host.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='orvunoInboxEmpty';e.textContent='Keine Nachrichten vorhanden.';host.append(e);return}for(const m of items){const a=document.createElement('article');a.className='orvunoInboxMsg'+(m.read_at?'':' unread');const h=document.createElement('h3');h.textContent=m.subject||'Nachricht';const meta=document.createElement('div');meta.className='orvunoInboxMeta';meta.textContent=(m.sender_label||'Nadena Games')+' · '+new Date(m.created_at).toLocaleString('de-DE');const body=document.createElement('div');body.className='orvunoInboxBody';body.textContent=m.body||'';a.append(h,meta,body);a.onclick=()=>mark(m,a);host.append(a)}}
async function mark(m,node){if(m.read_at)return;try{await api()?.rpc?.('orvuno_mark_admin_message_read',{p_message_id:m.id});m.read_at=new Date().toISOString();node.classList.remove('unread');badge()}catch(_){}}
async function load(force=false){const client=api();if(!client?.session?.access_token||busy||(!force&&Date.now()-lastLoad<45000))return;busy=true;try{const rows=await client.rpc('orvuno_get_admin_messages',{p_limit:80});items=Array.isArray(rows)?rows:[];lastLoad=Date.now();install();badge();if(document.getElementById('orvunoAdminInboxModal')?.classList.contains('show'))render()}catch(_){}finally{busy=false}}
function open(){install();document.getElementById('orvunoAdminInboxModal')?.classList.add('show');render();void load(true)}function close(){document.getElementById('orvunoAdminInboxModal')?.classList.remove('show')}
function sync(){const client=api();if(client?.session?.access_token){install();void load(false)}else{document.getElementById('orvunoAdminInboxButton')?.remove();document.getElementById('orvunoAdminInboxModal')?.remove()}}
for(const ev of ['world:access-granted','world:user-login','world:profile-updated'])window.addEventListener(ev,()=>setTimeout(sync,100));window.addEventListener('focus',sync);setInterval(()=>{if(document.visibilityState==='visible')sync()},120000);setTimeout(sync,1200);
})();
