// ORVUNO – Nadena Games Admin-Newsletter + Spieler-Postfach.
// Nutzt die bestehende ORVUNO-Sitzung und serverseitig geschützte RPCs/Edge-Bridge.
const ENDPOINT='https://ojhaeccyulyrwoxgeurf.supabase.co/functions/v1/orvuno-admin-messages';
const ADMIN_ROLES=new Set(['owner','admin','moderator','support']);
const state={messages:[],open:false,adminOpen:false};
const api=()=>window.worldAccounts?.authApi||null;
const currentUser=()=>window.worldCurrentUser||window.worldAccounts?.gameAccessGate?.user||window.worldServerAccountOverview?.user||null;
const role=()=>String(currentUser()?.admin_role||currentUser()?.adminRole||currentUser()?.role||'').toLowerCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{if(!v)return'–';const d=new Date(v);return Number.isNaN(d.getTime())?'–':d.toLocaleString('de-DE')};
function installStyle(){if(document.getElementById('orvuno-nadena-msg-style'))return;const s=document.createElement('style');s.id='orvuno-nadena-msg-style';s.textContent=`
.onm-btn{position:static;flex:0 0 auto;white-space:nowrap;border:1px solid #315272;border-radius:10px;padding:12px 16px;font-weight:850;cursor:pointer;background:#111f34;color:#edf6ff}.onm-btn.admin{border-color:#d29922;background:#2d2110;color:#ffd866}.onm-count{display:inline-grid;place-items:center;min-width:18px;height:18px;padding:0 5px;margin-left:5px;border-radius:999px;background:#e6495d;color:#fff;font-size:10px;font-weight:900}.onm-back{position:fixed;inset:0;z-index:100100;background:rgba(2,7,14,.84);display:grid;place-items:center;padding:16px}.onm-modal{width:min(900px,96vw);max-height:92vh;overflow:auto;border:1px solid #2c4565;border-radius:18px;background:#0c1626;color:#edf4ff;box-shadow:0 28px 90px #000a;font:14px/1.5 system-ui}.onm-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid #263b59;background:#101d30}.onm-head h2{margin:0}.onm-close,.onm-action{border:1px solid #3b597e;border-radius:9px;padding:9px 12px;background:#172a44;color:#fff;font-weight:800;cursor:pointer}.onm-body{padding:16px}.onm-card{padding:14px;margin-bottom:10px;border:1px solid #2a405e;border-radius:12px;background:#111e31}.onm-card.unread{border-color:#5a8fea;background:#142845}.onm-meta{display:flex;justify-content:space-between;gap:10px;color:#9db1ca;font-size:12px}.onm-card h3{margin:8px 0}.onm-empty,.onm-status{padding:12px;color:#aebed2}.onm-form{display:grid;gap:10px}.onm-form input,.onm-form textarea,.onm-form select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #344e6e;border-radius:9px;background:#08121f;color:#fff}.onm-form textarea{min-height:160px;resize:vertical}.onm-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}@media(max-width:700px){.onm-row{grid-template-columns:1fr}.onm-back{padding:6px}.onm-modal{max-height:97vh}}
`;document.head.append(s);}
async function loadMessages(){const a=api();if(!a?.rpc||!currentUser())return[];try{const rows=await a.rpc('orvuno_get_admin_messages',{p_limit:100});state.messages=Array.isArray(rows)?rows:[]}catch(e){console.warn('Nadena-Nachrichten konnten nicht geladen werden',e);state.messages=[]}syncButtons();return state.messages;}
function unread(){return state.messages.filter(x=>!x.read_at).length;}
function syncButtons(){const nav=document.getElementById('world-main-nav');if(!nav)return;let inbox=document.getElementById('orvuno-nadena-inbox');if(!inbox){inbox=document.createElement('button');inbox.id='orvuno-nadena-inbox';inbox.className='onm-btn';inbox.onclick=()=>openInbox();nav.append(inbox)}const n=unread();inbox.innerHTML=`📨 Nadena-Postfach${n?` <span class="onm-count">${n>99?'99+':n}</span>`:''}`;const allowed=ADMIN_ROLES.has(role());let admin=document.getElementById('orvuno-nadena-admin-msg');if(allowed&&!admin){admin=document.createElement('button');admin.id='orvuno-nadena-admin-msg';admin.className='onm-btn admin';admin.textContent='📣 Newsletter';admin.onclick=()=>openAdmin();nav.append(admin)}if(!allowed&&admin)admin.remove();}
function shell(title){installStyle();document.querySelector('.onm-back')?.remove();const back=document.createElement('div');back.className='onm-back';back.innerHTML=`<section class="onm-modal"><header class="onm-head"><h2>${esc(title)}</h2><button class="onm-close" type="button">✕ Schließen</button></header><div class="onm-body"></div></section>`;document.body.append(back);back.querySelector('.onm-close').onclick=()=>back.remove();back.onclick=e=>{if(e.target===back)back.remove()};return back.querySelector('.onm-body');}
async function markRead(id){try{await api()?.rpc('orvuno_mark_admin_message_read',{p_message_id:id});const m=state.messages.find(x=>String(x.id)===String(id));if(m)m.read_at=new Date().toISOString();syncButtons()}catch(e){console.warn('Nadena-Nachricht konnte nicht gelesen markiert werden',e)}}
async function openInbox(){const body=shell('Nadena Games · Postfach');body.innerHTML='<div class="onm-status">Nachrichten werden geladen …</div>';await loadMessages();if(!state.messages.length){body.innerHTML='<div class="onm-empty">Noch keine Nachrichten von Nadena Games.</div>';return}body.innerHTML='';for(const m of state.messages){const card=document.createElement('article');card.className='onm-card'+(!m.read_at?' unread':'');card.innerHTML=`<div class="onm-meta"><b>${esc(m.sender_label||'Nadena Games')}</b><span>${esc(date(m.created_at))}</span></div><h3>${esc(m.subject||'Nachricht')}</h3><div>${esc(m.body||'').replace(/\n/g,'<br>')}</div>`;card.onclick=()=>{if(!m.read_at){markRead(m.id);card.classList.remove('unread')}};body.append(card)}}
async function edge(action,payload={}){const a=api();if(!a)throw new Error('ORVUNO-Sitzung fehlt.');await a.ensureAccessToken?.();const token=a.session?.access_token;if(!token)throw new Error('Bitte erneut anmelden.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({action,...payload}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function openAdmin(){if(!ADMIN_ROLES.has(role()))return;const body=shell('ORVUNO · Newsletter');body.innerHTML=`<form class="onm-form" id="onmAdminForm"><label>Zielgruppe<select name="mode"><option value="all">Alle ORVUNO-Spieler</option><option value="one">Ein einzelner Spieler</option></select></label><label id="onmPlayerRow" hidden>Spieler<select name="player"><option value="">Wird geladen …</option></select></label><label>Betreff<input name="subject" maxlength="160" required></label><label>Nachricht<textarea name="body" maxlength="10000" required></textarea></label><button class="onm-action" type="submit">Nachricht senden</button><div class="onm-status" id="onmAdminStatus"></div></form>`;const f=body.querySelector('#onmAdminForm'),mode=f.elements.mode,player=f.elements.player,row=body.querySelector('#onmPlayerRow'),status=body.querySelector('#onmAdminStatus');let players=[];async function ensurePlayers(){if(players.length)return;status.textContent='Spielerliste wird geladen …';const out=await edge('list_players');players=Array.isArray(out.players)?out.players:[];player.innerHTML='<option value="">Spieler wählen …</option>'+players.map(p=>`<option value="${esc(p.id)}">${esc(p.display_name||p.username||p.email||`Spieler ${p.id}`)}${p.email?` · ${esc(p.email)}`:''}</option>`).join('');status.textContent=`${players.length.toLocaleString('de-DE')} Spieler verfügbar.`}mode.onchange=async()=>{row.hidden=mode.value!=='one';if(mode.value==='one')try{await ensurePlayers()}catch(e){status.textContent='❌ '+e.message}};f.onsubmit=async e=>{e.preventDefault();const subject=f.elements.subject.value.trim(),text=f.elements.body.value.trim();if(!subject||!text)return;const btn=f.querySelector('button[type=submit]');btn.disabled=true;status.textContent='Versand läuft …';try{if(mode.value==='one'){if(!player.value)throw new Error('Bitte einen Spieler wählen.');await edge('send_one',{playerId:player.value,subject,body:text})}else await edge('send_all',{subject,body:text});status.textContent='✅ Nachricht wurde gespeichert.';f.elements.subject.value='';f.elements.body.value=''}catch(err){status.textContent='❌ '+err.message}finally{btn.disabled=false}}}
function boot(){installStyle();syncButtons();void loadMessages();let tries=0;const timer=setInterval(()=>{tries++;syncButtons();if(currentUser()&&api()){void loadMessages();if(tries>10)clearInterval(timer)}if(tries>40)clearInterval(timer)},1000);for(const ev of ['world:access-granted','world:user-login','world:profile-updated','worldproject:profile-loaded'])window.addEventListener(ev,()=>{syncButtons();void loadMessages()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
